### ISSUE TITLE
crashes at call

### ISSUE THREAD

**Issue by T4mmi** [KitwareMedical/ITKIOScanco#25]
Hi, 
Saw that you wrapped the module to python,
tried to test it crashes at call :

```
conda create --name itk  python=3.5
conda activate itk 
conda install numpy pip ipython
pip install itk itk-ioscanco

ipython
import itk
reader = itk.ScancoImageIO.New()
```
then it crashes IPython without any warning :(

**Comment by sbonaretti** [comment]
Same here! Suggestions? Thanks!

**Comment by thewtex** [comment]
Thanks for the report.

This should hopefully be addressed when #26 is deployed.

**Comment by thewtex** [comment]
```
python -m pip install --upgrade itk-ioscanco
```

to obtain 0.4.0 should do the trick.

**Comment by sbonaretti** [comment]
Yes, it works! Thanks! :)
