### ISSUE TITLE
Reading .ISQ header

### ISSUE THREAD

**Issue by sbonaretti** [KitwareMedical/ITKIOScanco#27]
Hi,

Is there a function that reads and returns the header of .isq files? 

Thanks!
Serena

**Comment by thewtex** [comment]
A number of the import header elements are exposed in the `itk.ScancoImageIO` class:

https://github.com/KitwareMedical/ITKIOScanco/blob/36949ad4bd5354794362b069a21039ab83979803/include/itkScancoImageIO.h#L145-L211

**Comment by sbonaretti** [comment]
Thanks! Got it! For anybody how might need it in `python`:

After reading the image: 
```
ImageType = itk.Image[itk.ctype('signed short'), 3]
reader = itk.ImageFileReader[ImageType].New()
imageio = itk.ScancoImageIO.New()
reader.SetImageIO(imageio)
reader.SetFileName(file_name) # change to your filename here
reader.Update()
```
Get the header fields:
```
print(imageio.GetPatientIndex())
print(imageio.GetScannerID())
print(imageio.GetSliceThickness())
print(imageio.GetSliceIncrement())
print(imageio.GetStartPosition())
print(imageio.GetMuScaling())
print(imageio.GetNumberOfSamples())
print(imageio.GetNumberOfProjections())
print(imageio.GetScanDistance())
print(imageio.GetScannerType())
print(imageio.GetSampleTime())
print(imageio.GetMeasurementIndex())
print(imageio.GetSite())
print(imageio.GetReferenceLine())
print(imageio.GetReconstructionAlg())
print(imageio.GetEnergy())
print(imageio.GetIntensity())
print(imageio.GetPatientName())
```

**Comment by sbonaretti** [comment]
Hi, 
Is there any way to get `CreationDate` and `ModificationDate` in python? 
Thanks a lot,
Serena

**Comment by thewtex** [comment]
Hi @sbonaretti ,

Yes, this should do it: https://github.com/KitwareMedical/ITKIOScanco/pull/30
