### ISSUE TITLE
Attempting to build RemoteModule results in failure due to missing object download

### ISSUE THREAD

**Issue by hjmjohnson** [KitwareMedical/ITKIOScanco#28]
CMake Error at /Shared/sinapse/opt/iiai/apps/cmake/3.15.0/share/cmake-3.15/Modules/ExternalData.cmake:1121 (message):
  

  Object
  SHA512=9f03a48869d8b4ced44927a273f95f4d9985a644206145ff6580892242a42081c51865013cfc490c011a7a765dcf6764d98bee92da718829faa177e5540de211
  not found at:

    https://insightsoftwareconsortium.github.io/ITKTestingData/SHA512/9f03a48869d8b4ced44927a273f95f4d9985a644206145ff6580892242a42081c51865013cfc490c011a7a765dcf6764d98bee92da718829faa177e5540de211 ("HTTP response code said error")
    https://data.kitware.com:443/api/v1/file/hashsum/SHA512/9f03a48869d8b4ced44927a273f95f4d9985a644206145ff6580892242a42081c51865013cfc490c011a7a765dcf6764d98bee92da718829faa177e5540de211/download ("Timeout was reached")
    https://itk.org/files/ExternalData/SHA512/9f03a48869d8b4ced44927a273f95f4d9985a644206145ff6580892242a42081c51865013cfc490c011a7a765dcf6764d98bee92da718829faa177e5540de211 ("HTTP response code said error")
    https://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=9f03a48869d8b4ced44927a273f95f4d9985a644206145ff6580892242a42081c51865013cfc490c011a7a765dcf6764d98bee92da718829faa177e5540de211&algorithm=SHA512 (wrong hash SHA512=639526ba1271b833beeb026311a3d40d2b50b8480ce8e938e87ea0dfc9c84e76867be09043f9b15fc5b21d003580c6169f1ba59b2202686b80258d8993ab7a09)

**Comment by hjmjohnson** [comment]
@thewtex Matt, there seems to be a missing file needed for the remote module building as part of ITK.

**Comment by thewtex** [comment]
@hjmjohnson thanks for the report! The file is now uploaded:

  https://data.kitware.com/api/v1/file/5e559736af2e2eed35d4d8f2/download
