### ISSUE TITLE
Convert to Hounsfield units by default

### ISSUE THREAD

**Issue by dzenanz** [KitwareMedical/ITKIOScanco#41]
Currently, the reader does not do conversion to HU. We should enabled that by default.

**Comment by dzenanz** [comment]
@mkuczyns do you plan to work on this soon? If not, I could uncomment the [current conversion code](https://github.com/KitwareMedical/ITKIOScanco/blob/v0.8.0/src/itkScancoImageIO.cxx#L1015-L1023).

**Comment by mkuczyns** [comment]
@dzenanz thanks for notifying me. I can make those changes and submit a new PR in the next few days.

**Comment by dzenanz** [comment]
That would be great!
