### ISSUE TITLE
Is compressed data subject to rescaling?

### ISSUE THREAD

**Issue by dzenanz** [KitwareMedical/ITKIOScanco#54]
Currently, rescaling is done only if input image is [not compressed](https://github.com/KitwareMedical/ITKIOScanco/blob/a913b8736e53901edef3be2529d1eacdb3e5d88b/src/itkScancoImageIO.cxx#L1115):
https://github.com/KitwareMedical/ITKIOScanco/blob/a913b8736e53901edef3be2529d1eacdb3e5d88b/src/itkScancoImageIO.cxx#L1126-L1162
Should this be done in case of compression? If so, we should move the rescaling block from line 1126 to the end of the method, just after `delete[] input;` (currently on line 1294).

**Comment by mkuczyns** [comment]
Scanco images can only be compressed if they are segmentation files, however, they do not necessarily have to be compressed. I just tested the conversion from AIM to NIFTI on a binary AIM with and without compression. Both look fine with the only difference being the data value range (for compressed images the values are 0 and 127, for uncompressed images they are 24 and 90). We will need to move the rescaling to include compressed images to keep the original range of 0 to 127 from the Scanco system. I can quickly make this change.
