### ISSUE TITLE
installing itk-ioscanco is not working

### ISSUE THREAD

**Issue by bash403** [KitwareMedical/ITKIOScanco#61]
Hallo everyone, 

i am trying to install itk-ioscanco in order to read ISQ image, I have python 3.9 and tried to install ioscanco through 
 python3 -m pip install itk-ioscanco
but I always get this error: 
ERROR: Could not find a version that satisfies the requirement itk-ioscanco (from versions: none)
ERROR: No matching distribution found for itk-ioscanco
can anyone help with this thank you!

**Comment by dzenanz** [comment]
What happens if you do `python3 -m pip install --pre itk-ioscanco` (note addition of `--pre` argument)?

**Comment by thewtex** [comment]
Hi, Please try the latest version (0.10.0) and re-open if you still have issues.
