### ISSUE TITLE
Reading *.AIM contours fails

### ISSUE THREAD

**Issue by wallematthias** [KitwareMedical/ITKIOScanco#71]
When reading contours generated by Scanco (*.AIM) the following error is prompted: 

`TemplateTypeError: itk.Image is not wrapped for input type `itk.SC, int`.
`
Would it be possible to cast these images to a different type? They typically only contain a binary classification for the trabecular/cortical contours.

**Comment by dzenanz** [comment]
From the [docs](https://itkpythonpackage.readthedocs.io/en/master/Quick_start_guide.html#input-output-io):
```
# Read in with a specific pixel type.
image = itk.imread('image.aim', itk.UC)
```
Does this work?

**Comment by wallematthias** [comment]
That works thank you!
